<img style="float: left;;" src='../Figures/iteso.jpg' width="50" height="100"/></a>

# <center> <font color= #000047> Repaso de la Librería NumPy</font> </center>



# NumPy 

NumPy es una poderosa librería de álgebra lineal para Python. Lo que lo hace tan importante es que casi todas las librerías en el ecosistema de <a href='https://pydata.org/'>PyData</a> (pandas, scipy, scikit-learn, etc.) utilizan NumPy como uno de sus principales componentes básicos. 

NumPy también es increíblemente rápido, ya que tiene enlaces a bibliotecas C.

Aquí repasaremos los conceptos básicos de NumPy.

## Usando NumPy


In [4]:
import numpy as np


NumPy tiene muchas funciones y capacidades integradas. No veremos todos, nos centraremos en algunos de los aspectos más importantes de NumPy qué nos serán de utilidad en el curso como son: vectores, arreglos, matrices y generación de números aleatorios. 

# Arreglos en NumPy 

Los arreglos de NumPy son la principal forma en que utilizaremos esta librería a lo largo del curso. Los arreglos en NumPy se construyen de dos formas: vectores y matrices. Los vectores son matrices estrictamente unidimensionales (1D) y las matrices son elementos en 2D (pero se debe tener en cuenta que una matriz puede tener solo una fila o una columna) no son estrictamente cuadradas.

## Creando Arreglos en NumPy

### De una Lista de Python 

Podemos crear un arreglo directamente de una lista o listas de listas:



In [5]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [8]:
my_array = np.array(my_list)
my_array.reshape(3,1)

array([[1],
       [2],
       [3]])

In [10]:
my_matrix = np.array([[1,2,3],
                     [4,5,6],
                    [7,8,9]])
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Métodos incorporados en NumPy

Hay muchas formas de como generar arreglos usando métodos incorporados.

### arange

Devuelve valores espaciados uniformemente dentro de un intervalo dado. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [11]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a = np.arange(0,11,2)
a

array([ 0,  2,  4,  6,  8, 10])

### Creando arreglos de Ceros (zeros) y Unos (ones)

Podemos generar matrices de ceros ó unos. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [15]:
a = np.zeros(3,dtype=int)
a


array([0, 0, 0])

In [16]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [17]:
np.ones(3)

array([1., 1., 1.])

In [19]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
5*np.ones((5,5),dtype=int)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

### linspace 
Este método devuelve números espaciados uniformemente durante un intervalo especificado.[[referencia](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [23]:
np.linspace(0,10,3,dtype=int)

array([ 0,  5, 10])

In [24]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

<font color=green>Note que `.linspace()` *incluye* el valor de paro. Para obtener un arreglo con fracciones comunes, hay que aumentar el numero de elementos:</font>

### eye

Mediante este método podemos crear la matriz identidad.[[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [26]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## Random 
Numpy también tiene muchas formas de crear arreglos de números aleatorios:

### rand

Mediante este método podemos crear un arreglo de un tamaño dado con muestras aleatorias de una distribución uniforme en el intervalo ``[0, 1)``.[[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [27]:
np.random.rand()

0.8703268705890096

In [28]:
np.random.rand(3)

array([0.3331014 , 0.3107855 , 0.50656462])

In [29]:
np.random.rand(3,3
              )

array([[0.22825201, 0.32516199, 0.43188023],
       [0.45982527, 0.65246897, 0.15783034],
       [0.8230502 , 0.74139662, 0.53027979]])

In [33]:
np.random.randint(0,20)

3

### randn

Este método devuelve una muestra (o muestras) de la distribución "normal estándar" [σ = 1] A diferencia de **rand**, que es uniforme, es más probable que aparezcan valores más cercanos a cero. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]


In [36]:
np.random.randn(2,2
               )

array([[ 6.39806407e-01,  1.32906364e+00],
       [ 1.15967314e+00, -1.04989517e-04]])

### randint
Devuelve números enteros aleatorios de un intervalo `mínimo` (inclusive) a `máximo` (exclusivo).  [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [37]:
np.random.randint(1,100,5)

array([54, 73, 87, 73, 42])

### seed
Se puede utilizar para establecer el estado aleatorio, de modo que se puedan reproducir los mismos resultados "aleatorios". [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [41]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Atributos y métodos de un Arreglo

Analicemos algunos atributos y métodos útiles para un arreglo:

In [43]:
arr = np.arange(20
               )
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [44]:
b = np.random.randint(0,50,10)
b

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

## Reshape
Devuelve una matriz que contiene los mismos datos con una nueva forma. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [61]:
c = arr.reshape(5,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

### max, min, argmax, argmin

Estos son métodos útiles para encontrar valores máximos o mínimos. O para encontrar el índice donde tenemos valores máximos o mínimos:

In [62]:
arr.max()

19

In [63]:
arr.min()

0

In [64]:
arr.argmin()

0

In [65]:
arr.argmax()

19

## Shape

Shape es un atributo que tienen los arreglos (no un método): [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [67]:
c.shape

(5, 4)

In [68]:
c.reshape(4,5).shape

(4, 5)

### dtype

Podemos también obtener el tipo de datos del objeto en el arreglo. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [69]:
c.dtype

dtype('int32')

In [71]:
0000 0000 ->        2^0

SyntaxError: invalid syntax (<ipython-input-71-84a8f6b30288>, line 1)