In [1]:
!pip install gower

  Created wheel for gower: filename=gower-0.0.5-py3-none-any.whl size=4237 sha256=1391c4c5492bc723ce96e8309c0d6c8a833ed8d74fc316b0fffbf8ab21e7071a
  Stored in directory: c:\users\carlosruizmoreno\appdata\local\pip\cache\wheels\0e\4a\62\f296d39ee4f9ffc44a8d44413dc8ce99ed022c581352312c20
Successfully built gower


In [9]:
import gower
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.spatial.distance as sc

### Ejemplo

In [31]:
df = pd.DataFrame([[1,2.6,'A'],[12,5,'X'],[4,7,'A']])
df.columns = ['Num_1','Num_2','Num_3']
df

Num_1  Num_2 Num_3
0      1    2.6     A
1     12    5.0     X
2      4    7.0     A

In [32]:
delta_1 = sc.squareform(sc.pdist(df[['Num_1']],'cityblock'))
delta_1

array([[ 0., 11.,  3.],
       [11.,  0.,  8.],
       [ 3.,  8.,  0.]])

In [33]:
np.ptp(df['Num_1'])

11

In [34]:
delta_1 = delta_1/max(np.ptp(df['Num_1']),1)
delta_1

array([[0.        , 1.        , 0.27272727],
       [1.        , 0.        , 0.72727273],
       [0.27272727, 0.72727273, 0.        ]])

In [35]:
delta_2 = sc.squareform(sc.pdist(df[['Num_2']],'cityblock'))
delta_2

array([[0. , 2.4, 4.4],
       [2.4, 0. , 2. ],
       [4.4, 2. , 0. ]])

In [36]:
delta_2 = delta_2/max(np.ptp(df['Num_2']),1)
delta_2

array([[0.        , 0.54545455, 1.        ],
       [0.54545455, 0.        , 0.45454545],
       [1.        , 0.45454545, 0.        ]])

In [37]:
dummy_df = pd.get_dummies(df['Num_3'])
dummy_df

A  X
0  1  0
1  0  1
2  1  0

In [38]:
delta_3 = sc.squareform(sc.pdist(dummy_df,'dice'))
delta_3

array([[0., 1., 0.],
       [1., 0., 1.],
       [0., 1., 0.]])

In [39]:
w1=w2=w3=1

In [40]:
gower_sim = (w1*delta_1 + w2*delta_2 + w3*delta_3)/(w1+w2+w3)
gower_sim

array([[0.        , 0.84848485, 0.42424242],
       [0.84848485, 0.        , 0.72727273],
       [0.42424242, 0.72727273, 0.        ]])

In [41]:
gower_sim_lib = gower.gower_matrix(df)
gower_sim_lib

array([[0.        , 0.8484848 , 0.4242424 ],
       [0.8484848 , 0.        , 0.72727275],
       [0.4242424 , 0.72727275, 0.        ]], dtype=float32)

### Ejemplo 2

In [42]:
# Creating a dictionary with the data
dictionary = {"age": [22, 25, 30, 38, 42, 47, 55, 62, 61, 90], 
              "gender": ["M", "M", "F", "F", "F", "M", "M", "M", "M", "M"], 
              "civil_status": ["SINGLE", "SINGLE", "SINGLE", "MARRIED", "MARRIED", "SINGLE", "MARRIED", "DIVORCED", "MARRIED", "DIVORCED"], 
              "salary": [18000, 23000, 27000, 32000, 34000, 20000, 40000, 42000, 25000, 70000], 
              "has_children": [False, False, False, True, True, False, False, False, False, True], 
              "purchaser_type": ["LOW_PURCHASER", "LOW_PURCHASER", "LOW_PURCHASER", "HEAVY_PURCHASER", "HEAVY_PURCHASER", "LOW_PURCHASER", "MEDIUM_PURCHASER", "MEDIUM_PURCHASER", "MEDIUM_PURCHASER", "LOW_PURCHASER"]}
 
# Creating a Pandas DataFrame from the dictionary
dataframe = pd.DataFrame.from_dict(dictionary)

In [43]:
dataframe

age gender civil_status  salary  has_children    purchaser_type
0   22      M       SINGLE   18000         False     LOW_PURCHASER
1   25      M       SINGLE   23000         False     LOW_PURCHASER
2   30      F       SINGLE   27000         False     LOW_PURCHASER
3   38      F      MARRIED   32000          True   HEAVY_PURCHASER
4   42      F      MARRIED   34000          True   HEAVY_PURCHASER
5   47      M       SINGLE   20000         False     LOW_PURCHASER
6   55      M      MARRIED   40000         False  MEDIUM_PURCHASER
7   62      M     DIVORCED   42000         False  MEDIUM_PURCHASER
8   61      M      MARRIED   25000         False  MEDIUM_PURCHASER
9   90      M     DIVORCED   70000          True     LOW_PURCHASER

In [45]:
distance_gower = gower.gower_matrix(dataframe)
distance_gower

array([[0.        , 0.02337858, 0.21512066, 0.7507542 , 0.7669683 ,
        0.06768477, 0.48472852, 0.50829566, 0.45135745, 0.6666667 ],
       [0.02337858, 0.        , 0.19174208, 0.72737557, 0.74358976,
        0.06353696, 0.46134993, 0.48491704, 0.42797887, 0.6432881 ],
       [0.21512066, 0.19174208, 0.        , 0.5356335 , 0.55184764,
        0.23076923, 0.60294116, 0.6265083 , 0.58239067, 0.7848793 ],
       [0.7507542 , 0.72737557, 0.5356335 , 0.        , 0.01621418,
        0.72718704, 0.5673077 , 0.7575415 , 0.5788084 , 0.7492459 ],
       [0.7669683 , 0.74358976, 0.55184764, 0.01621418, 0.        ,
        0.7237934 , 0.5510935 , 0.7413273 , 0.5754148 , 0.7330317 ],
       [0.06768477, 0.06353696, 0.23076923, 0.72718704, 0.7237934 ,
        0.        , 0.41704375, 0.44061086, 0.3836727 , 0.5989819 ],
       [0.48472852, 0.46134993, 0.60294116, 0.5673077 , 0.5510935 ,
        0.41704375, 0.        , 0.19023378, 0.06278281, 0.6819382 ],
       [0.50829566, 0.48491704, 0.6265083

In [47]:
new_cols = [f'customer_{c}' for c in range (0, len(dataframe))]
new_cols

['customer_0',
 'customer_1',
 'customer_2',
 'customer_3',
 'customer_4',
 'customer_5',
 'customer_6',
 'customer_7',
 'customer_8',
 'customer_9']

In [48]:
DC = pd.DataFrame(distance_gower, columns=new_cols, index=new_cols)
DC

customer_0  customer_1  customer_2  customer_3  customer_4  \
customer_0    0.000000    0.023379    0.215121    0.750754    0.766968   
customer_1    0.023379    0.000000    0.191742    0.727376    0.743590   
customer_2    0.215121    0.191742    0.000000    0.535634    0.551848   
customer_3    0.750754    0.727376    0.535634    0.000000    0.016214   
customer_4    0.766968    0.743590    0.551848    0.016214    0.000000   
customer_5    0.067685    0.063537    0.230769    0.727187    0.723793   
customer_6    0.484729    0.461350    0.602941    0.567308    0.551094   
customer_7    0.508296    0.484917    0.626508    0.757541    0.741327   
customer_8    0.451357    0.427979    0.582391    0.578808    0.575415   
customer_9    0.666667    0.643288    0.784879    0.749246    0.733032   

            customer_5  customer_6  customer_7  customer_8  customer_9  
customer_0    0.067685    0.484729    0.508296    0.451357    0.666667  
customer_1    0.063537    0.461350    0.484917    0.427979    0.643288  
customer_2    0.230769    0.602941    0.626508    0.582391    0.784879  
customer_3    0.727187    0.567308    0.757541    0.578808    0.749246  
customer_4    0.723793    0.551094    0.741327    0.575415    0.733032  
customer_5    0.000000    0.417044    0.440611    0.383673    0.598982  
customer_6    0.417044    0.000000    0.190234    0.062783    0.681938  
customer_7    0.440611    0.190234    0.000000    0.223605    0.491704  
customer_8    0.383673    0.062783    0.223605    0.000000    0.715309  
customer_9    0.598982    0.681938    0.491704    0.715309    0.000000

In [49]:
DC.loc['customer_4'].sort_values()

customer_4    0.000000
customer_3    0.016214
customer_6    0.551094
customer_2    0.551848
customer_8    0.575415
customer_5    0.723793
customer_9    0.733032
customer_7    0.741327
customer_1    0.743590
customer_0    0.766968
Name: customer_4, dtype: float32

### Actividad recomendación de peliculas

In [10]:
data = pd.read_excel('..Data/peliculas.xlsx')
data

FileNotFoundError: [Errno 2] No such file or directory: '..Data/peliculas.xlsx'