<img src="iteso_horizontal.png">

<h1><center>DEPARTAMENTO DE MATEMÁTICAS Y FÍSICA</center></h1>

<h1><center>Tarea 1 : Ejercicios con librería NumPy y Pandas</center></h1>


<h1> Nombre: Carlos Enrique Ruiz Moreno </h1>
<hr>   

Ahora que hemos hecho el repaso de la líbreria de NumPy, es momento de probar los conocimientos adquiridos. 

<div class="alert alert-danger" style="margin: 10px"><strong>NOTA IMPORTANTE!</strong> Asegúrese de no escribir código en las celdas donde se muestra ejemplificada la salida (etiquetada como "no escribir aquí") <br> de lo contrario, terminará reescribiendo la salida esperada.</div>

#### 1. importar NumPy como np

In [24]:
import numpy as np

#### 2. Crear un arreglo de ceros de tamaño 10 

In [25]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
# NO ESCRIBIR AQUÍ

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Crear un arreglo de ceros de tamaño 10 

In [26]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
# NO ESCRIBIR AQUÍ

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Crear un arreglo de cincos de tamaño 10 

In [27]:
5*np.ones(10)


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [4]:
# NO ESCRIBIR AQUÍ

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Crear un arreglo de enteros que contenga elementos del 10 al 50

In [28]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [5]:
# NO ESCRIBIR AQUÍ

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Crear un arreglo de todos los enteros pares en el intervalo de 10 a 50

In [29]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [6]:
# NO ESCRIBIR AQUÍ

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Crear una matriz de 3x3 con valores en el rango de 0 a 8.

In [30]:
np.arange(0,9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# NO ESCRIBIR AQUÍ

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Crear una matriz identidad de 3x3

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# NO ESCRIBIR AQUÍ

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Usa NumPy para generar un número aleatorio entre 0 y 1 <br><br>&emsp;NOTA: Tu resultado puede ser diferente al que se muestra en el resultado de ejemplo.

In [32]:
np.random.rand()

0.5274836095726914

In [26]:
# NO ESCRIBIR AQUÍ

#### 10. Usa NumPy para generar un arreglo que contenga 25 números aleatorios muestreados a partir de una distribución normal estándar.<br><br>&emsp;&ensp;NOTA: Los valores de su resultado pueden ser diferentes de los que se muestran en el resultado de ejemplo.

In [33]:
np.random.randn(25)

array([ 0.85160468,  0.63089439,  0.35267154, -1.166316  , -2.0599236 ,
        1.67647331, -0.3790807 ,  0.77229641, -0.37442645,  0.06026156,
       -0.19080906, -0.57598204,  0.18296179,  0.01010206,  0.69685249,
        0.46241782, -1.29597382, -0.33225084, -1.96100274, -0.81078665,
       -1.13750601,  0.58984978,  0.2625538 ,  0.06555616, -0.10483428])

In [10]:
# NO ESCRIBIR AQUÍ

array([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
        1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
        0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
       -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
        1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

#### 11. Crea la matriz que se muestra en la salida de ejemplo:

In [34]:
np.arange(0.01,1.01,.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [11]:
# NO ESCRIBIR AQUÍ

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 12. Crea una matriz de tamaño 20 linealmente espaciada en el intervalo de 0 a 1:

In [35]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [12]:
# NO ESCRIBIR AQUÍ

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Indexación y Selección en Numpy 

Ahora se le dará una matriz inicial (¡asegúrese de ejecutar la celda a continuación!) Y se le pedirá que replique las salidas de la matriz que se muestra en la salida de ejemplo:


In [36]:
# EJECUTAR ESTA CELDA. ES NUESTRA MATRIZ DE INICIO
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Escriba código que reproduzca el resultado que se muestra a continuación.<br><br>&emsp;&ensp;Tenga cuidado de no ejecutar la celda inmediatamente arriba de la salida (etiquetada como: "NO ESCRIBIR AQUI"), de lo contrario no podrá ver el resultado de la salida.

In [37]:
# CÓDIGO AQUÍ
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [14]:
# NO ESCRIBIR AQUÍ

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Utilizando el resultado anterior escriba código que reproduzca el resultado que se muestra a continuación.

In [38]:
# CÓDIGO AQUÍ
mat[3,4]

20

In [15]:
# NO ESCRIBIR AQUÍ

20

#### 15. Utilizando el resultado de Out[14] Escriba código que reproduzca el resultado que se muestra a continuación.

In [39]:
# CÓDIGO AQUÍ
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [16]:
# NO ESCRIBIR AQUÍ

array([[ 2],
       [ 7],
       [12]])

#### 16. Utilizando la matriz contenida en la variable mat, escriba código que reproduzca el resultado que se muestra a continuación.

In [41]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [17]:
# NO ESCRIBIR AQUÍ

array([21, 22, 23, 24, 25])

#### 17. Utilizando la matriz contenida en la variable mat, escriba código que reproduzca el resultado que se muestra a continuación.

In [42]:
mat[3:5]


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
# NO ESCRIBIR AQUÍ

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Operaciones con NumPy

#### 18. Obtenga la suma de todos los valores en mat

In [43]:
mat.sum()

325

In [19]:
# NO ESCRIBIR AQUÍ

325

#### 19. Obtenga la desviación estándar de todos los valores en mat.

In [44]:
mat.std()

7.211102550927978

In [20]:
# NO ESCRIBIR AQUÍ

7.211102550927978

#### 20. Obtenga la suma de todas las columnas en mat

In [45]:
mat


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
mat[:,0:5].sum()

325

In [21]:
# NO ESCRIBIR AQUÍ

array([55, 60, 65, 70, 75])

## Operaciones con Pandas

**21. importar la librería de pandas**

In [2]:
import pandas as pd

**22. Lea el archivo bank.csv que se encuentra en la carpeta raíz. ¡Presta mucha atención a la ubicación del archivo .csv!.**

In [3]:
df = pd.read_csv('../Data/bank.csv')

**23. Mustre las primero 5 filas del dataset**

In [5]:
df.head(5)

age          job  marital  education default  balance housing loan  \
0   30   unemployed  married    primary      no     1787      no   no   
1   33     services  married  secondary      no     4789     yes  yes   
2   35   management   single   tertiary      no     1350     yes   no   
3   30   management  married   tertiary      no     1476     yes  yes   
4   59  blue-collar  married  secondary      no        0     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome   y  
0  cellular   19   oct        79         1     -1         0  unknown  no  
1  cellular   11   may       220         1    339         4  failure  no  
2  cellular   16   apr       185         1    330         1  failure  no  
3   unknown    3   jun       199         4     -1         0  unknown  no  
4   unknown    5   may       226         1     -1         0  unknown  no

**24. Calcule el promedio de la edad de las personas del dataset**

In [15]:
df.iloc[:,0].mean()

41.17009511170095

**25. ¿Cuál es el status marital de la persona más joven en el dataset?**



In [50]:
# df[df['age'] == age.min()]
df[df['age'].min()]

KeyError: 19

**26. ¿Cuántas categorías de trabajos únicos existen en el dataset?**

In [16]:
df['job'].unique()

array(['unemployed', 'services', 'management', 'blue-collar',
       'self-employed', 'technician', 'entrepreneur', 'admin.', 'student',
       'housemaid', 'retired', 'unknown'], dtype=object)

**27. Muestre cuántas personas hay por categoría de trabajo**

In [52]:
df['job'].value_counts()

management       969
blue-collar      946
technician       768
admin.           478
services         417
retired          230
self-employed    183
entrepreneur     168
unemployed       128
housemaid        112
student           84
unknown           38
Name: job, dtype: int64

**28. ¿Cuál es el porcentaje de las personas en el dataset que están casadas?**

In [53]:
100*(df['marital'].value_counts(len))

married     61.866844
single      26.454324
divorced    11.678832
Name: marital, dtype: float64

**29. En el dataset existe una columna etiquetada como: "default". Use el comando .map() para crear una nueva columna llamada "default_code" que contenga el valor 0 si el valor de la columna es "no", o 1 si el valor en la columna esta etiquetada como "si". Muestre los 5 primeros valores de esta nueva columna**


In [ ]:
# código aquí

**30. Usando el método pandas .apply (), cree una nueva columna llamada "marital_code". Esta columna solo contendrá un código abreviado de la posible primera letra del estado civil. (Por ejemplo, "m" para "casado", "s" para "soltero", etc.**

In [ ]:
# código aquí

**31. ¿Cuál fue el trabajp con duración más larga?**

In [ ]:
# código aquí

**32. ¿Cuál es el nivel de educación más común para las personas que están desempleadas?**

In [ ]:
# código aquí

**23. ¿Cuál es la edad promedio para estar desempleado?**

In [60]:
df[df['job'] == 'unemployed'].groupby('age').mean()

balance        day     duration   campaign       pdays  previous
age                                                                      
24    119.000000  15.000000    51.000000   1.000000   -1.000000  0.000000
25    178.000000  11.000000   242.000000  11.000000   -1.000000  0.000000
26    650.250000  27.500000   451.500000   5.500000   -1.000000  0.000000
27   1638.500000   4.000000    85.500000   1.500000   54.500000  1.000000
28    325.000000  10.000000   413.666667   2.333333   -1.000000  0.000000
29    691.000000  21.666667   389.333333   1.333333   -1.000000  0.000000
30    445.166667  17.500000   316.666667   2.333333   -1.000000  0.000000
31   1554.000000  21.375000   359.625000   2.625000   -0.625000  0.125000
32    549.200000  12.200000   277.600000   2.800000   -1.000000  0.000000
33    229.666667  19.666667   277.000000  10.000000   -1.000000  0.000000
34    138.333333  14.000000   119.333333   1.333333   -1.000000  0.000000
35   1221.750000  16.250000   594.500000   4.000000   74.500000  1.000000
36   1995.750000  22.500000   391.250000   2.500000   45.000000  0.250000
37   2181.000000   7.666667   293.666667   1.000000   60.000000  0.333333
38    728.666667  18.000000   392.833333   2.833333   -1.000000  0.000000
39    270.000000   3.000000   116.000000   1.000000   -1.000000  0.000000
40    242.000000  12.666667   223.333333   1.333333  215.000000  3.000000
41   1255.333333  16.333333   193.333333   3.000000   -1.000000  0.000000
42   2525.200000  26.400000   135.000000   3.200000  116.200000  1.000000
43   2248.666667  15.166667   214.666667   1.833333   15.000000  0.166667
44   2164.750000  16.000000   184.250000   1.500000   -1.000000  0.000000
45    354.000000  16.500000    91.000000   1.250000   80.500000  1.000000
46   1420.333333  12.333333   325.666667   1.333333   -1.000000  0.000000
47   1678.000000  16.500000   246.000000   2.000000  120.000000  0.500000
48   1768.500000  10.500000   314.750000   3.250000   69.750000  1.000000
49    189.500000  16.666667   147.166667   1.666667  185.333333  1.833333
50   1469.500000  18.000000   210.000000   2.750000   -1.000000  0.000000
51   1243.750000  14.500000   222.000000   1.750000   90.250000  0.250000
52     39.000000  19.000000   202.500000   1.500000   -1.000000  0.000000
53    537.000000   6.500000   422.500000   1.000000   90.000000  7.000000
54    541.000000   3.000000   237.000000   3.000000   -1.000000  0.000000
55   2596.000000  13.500000   283.000000   2.500000   92.500000  1.500000
56   1518.000000  11.000000   585.250000   2.500000   -1.000000  0.000000
57      0.000000  14.000000   318.500000   1.000000   -1.000000  0.000000
58   1050.666667  20.666667   101.000000   3.666667   -1.000000  0.000000
59   1460.500000  16.500000  1638.000000   1.500000   -1.000000  0.000000
60    385.000000   4.000000    80.000000   1.000000   -1.000000  0.000000